@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ModBookParser" as ModBookParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteModCommand" as DeleteModCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete mod 1", GuiState.DETAILS)
activate LogicManager

LogicManager -> ModBookParser : parseCommand("delete mod 1", GuiState.DETAILS)
activate ModBookParser

create DeleteCommandParser
ModBookParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> ModBookParser
deactivate DeleteCommandParser

ModBookParser -> DeleteCommandParser : parse("mod 1", GuiState.DETAILS)
activate DeleteCommandParser

create DeleteModCommand
DeleteCommandParser -> DeleteModCommand
activate DeleteModCommand

DeleteModCommand --> DeleteCommandParser : d
deactivate DeleteModCommand

DeleteCommandParser --> ModBookParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> ModBookParser
destroy DeleteCommandParser

ModBookParser --> LogicManager : d
deactivate ModBookParser

LogicManager -> DeleteModCommand : execute()
activate DeleteModCommand

DeleteModCommand -> Model : deleteModule(module)
activate Model

Model --> DeleteModCommand
deactivate Model

create CommandResult
DeleteModCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteModCommand
deactivate CommandResult

DeleteModCommand --> LogicManager : result
deactivate DeleteModCommand

[<--LogicManager
deactivate LogicManager
@enduml
