@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyModBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class ModBook
Class ReadOnlyModBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniqueModuleList
Class Module
Class Exam
Class ModuleName
Class ModuleCode
Class Lesson

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ModBook .up.|> ReadOnlyModBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyModBook
ModelManager -left-> "1" ModBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

ModBook *--> "1" UniqueModuleList
UniqueModuleList --> "~* all" Module
Module *--> "1" ModuleCode
Module *--> "0..1" ModuleName
Module *--> "*" Exam
Module *--> "*" Lesson

ModuleCode -[hidden]right-> ModuleName
ModuleName -[hidden]right-> Exam
Exam -[hidden]right-> Lesson

ModelManager -->"~* filtered" Module
@enduml
