@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "ModBook Storage" #F4F6F6{
Interface ModBookStorage <<Interface>>
Class JsonModBookStorage
Class JsonSerializableModBook
Class JsonAdaptedModule
Class JsonAdaptedLesson
Class JsonAdaptedExam
Class JsonAdaptedTimeslot
Class JsonAdaptedModBookTime
Class JsonAdaptedModBookDate
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" ModBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ModBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonModBookStorage .up.|> ModBookStorage
JsonModBookStorage ..> JsonSerializableModBook
JsonSerializableModBook --> "*" JsonAdaptedModule
JsonAdaptedModule --> "*" JsonAdaptedLesson
JsonAdaptedModule --> "*" JsonAdaptedExam
JsonAdaptedLesson --> "1" JsonAdaptedTimeslot
JsonAdaptedExam --> "1" JsonAdaptedTimeslot
JsonAdaptedExam --> "1" JsonAdaptedModBookDate
JsonAdaptedTimeslot --> "2" JsonAdaptedModBookTime

@enduml
